spring:
  application:
    name: trackerforce-identity-service
  data:
    mongodb:
      database: trackerforce
      uri: mongodb://localhost:27017

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      group:
        custom:
          show-components: always
          show-details: always

service:
  jwt:
    secret: 2BB80D537B1DA3E38BD30361AA855686BDE0EACD7162FEF6A25FE97BF527A25B
    expire: 15
  endpoint:
    allowed-addresses: >
     127.0.0.1,
     10.0.0.2
    allowed-endpoints: >
     /v3/api-docs,
     /*/swagger*/**,
     /*/authenticate,
     /*/register,
     /*/activate,
     /service/check
  management:
    url: http://127.0.0.1:8090

server:
  port: 8070
  error:
    include-message: always