spring:
  application:
    name: trackerforce-identity-service
  data:
    mongodb:
      database: trackerforce
      uri: mongodb://master:masterpassword@localhost:27017

service:
  package-name: com.trackerforce.identity.controller
  title: Trackerforce Identity
  description: Identity Service for Trackerforce API
  version: 0.0.2
  jwt:
    secret: 2BB80D537B1DA3E38BD30361AA855686BDE0EACD7162FEF6A25FE97BF527A25B
    expire: 15
  endpoint:
    allowed-addresses: >
     127.0.0.1,
     10.0.0.2
    allowed-endpoints: >
     /v2/api-docs,
     /**/swagger*/**,
     /**/authenticate,
     /**/register,
     /**/activate,
     /service/check
  management:
    url: http://127.0.0.1:8090

server:
  port: 8070
  error:
    include-message: always