spring:
  profiles:
    active: dev

service:
  docs:
    title: Trackerforce Management
    description: Business Service for Trackerforce API
    version: 0.0.2
    url: ${SERVER_URL:http://localhost:8090}
    license:
      type: MIT
      url: https://github.com/trackerforce/trackerforce-services/blob/master/LICENSE
    contact:
      author: Roger Floriano (petruki)
      email: trackerforce.project@gmail.com