spring:
  application:
    name: trackerforce-session-service
  data:
    mongodb:
      database: tfs
      uri: mongodb://master:masterpassword@localhost:27017

service:
  package-name: com.trackerforce.session.controller
  title: Trackerforce Session
  description: Session Service for Trackerforce API
  version: 0.0.2
  jwt:
    secret: 2BB80D537B1DA3E38BD30361AA855686BDE0EACD7162FEF6A25FE97BF527A25B
    expire: 60
  endpoint:
    allowed-addresses: >
     127.0.0.1,
     10.0.0.2
    allowed-endpoints: >
     /v2/api-docs,
     /swagger.*,
     /service/check,
     /management/agent/v1/activate
  identity:
    url: http://127.0.0.1:8070
  management:
    url: http://127.0.0.1:8090
  queue:
    url: http://127.0.0.1:8060

server:
  error:
    include-message: always
  port: 8080