spring:
  application:
    name: trackerforce-session-service
  data:
    mongodb:
      database: tfs
      uri: ${MONGODB_URL}

service:
  jwt:
    secret: ${JWT_SECRET}
    expire: ${JWT_EXPIRETIME:60}
  endpoint:
    allowed-addresses: ${WHITELIST}
    allowed-endpoints: >
     /service/check,
     /management/agent/v1/activate
  identity:
    url: http://127.0.0.1:8070
  management:
    url: http://127.0.0.1:8090
  queue:
    url: http://127.0.0.1:8060

server:
  error:
    include-message: always
  port: 8080