spring:
  application:
    name: trackerforce-session-service
  data:
    mongodb:
      database: tfs
      uri: ${MONGODB_URL}

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      group:
        custom:
          show-components: always
          show-details: always

service:
  package-name: com.trackerforce.session.controller
  title: Trackerforce Session
  description: Session Service for Trackerforce API
  version: 0.0.2
  jwt:
    secret: ${JWT_SECRET}
    expire: ${JWT_EXPIRETIME:60}
  endpoint:
    allowed-addresses: ${WHITELIST}
    allowed-endpoints: >
     /v2/api-docs,
     /service/check,
     /management/agent/v1/activate
  identity:
    url: http://127.0.0.1:8070
  management:
    url: http://127.0.0.1:8090
  queue:
    url: http://127.0.0.1:8060

server:
  error:
    include-message: always
  port: 8080