spring:
  profiles:
    active: dev

service:
  docs:
    title: Trackerforce Session
    description: Session Service for Trackerforce API
    version: 0.0.2-SNAPSHOT
    url: ${SERVER_URL}
    license:
      type: MIT
      url: https://github.com/trackerforce/trackerforce-services/blob/master/LICENSE
    contact:
      author: Roger Floriano (petruki)
      email: trackerforce.project@gmail.com