name: Management Service Workflow

on:
  push:
    branches: [master]
    paths:
      - 'trackerforce-management/**'
      - 'trackerforce-common/**'
      - 'trackerforce-common-tenancy/**'
  pull_request:
    branches: [master]
    paths:
      - 'trackerforce-management/**'
      - 'trackerforce-common/**'
      - 'trackerforce-common-tenancy/**'

jobs:
  build:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom_management.xml
